config/routes.rb
Blog::Application.routes.draw do
  devise_for :users
  get "welcome/index"
  resources :posts do
  end

  resources :pictures

   root 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
belongs_to :user
#has_attached_file :pic, :styles =>
#    { :medium => "300x300>", :thumb => "100x100>" }


has_attached_file :pic, :url => '/system/:attachment/:id/:style/:basename.:extension',
                  :path => ':rails_root/public/system/:attachment/:id/:style/:basename.:extension',
                  :styles => lambda { |a| a.instance.images_styles? ? {:medium => '500x500>', :other => '640x530', :thumb => '500x500>'} : {} },
                   presence: true

validates_attachment :pic, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
#has_attached_file :attach

def images_styles?
  if pic_content_type == 'image/jpeg' || pic_content_type == 'image/jpg' || pic_content_type == 'image/png' || pic_content_type == 'image/gif'
    true
  else
    false
  end
end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true,
            length: {minimum: 5 }


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :pictures, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
  @picture = Picture.new
  end

  def create
  puts "aaaaaaaaaaaaaaaaaaaaaaaaaa",params.inspect
  if params[:picture].present?
  @picture = Picture.new(pic_params)
  @picture.save
    redirect_to pictures_path
  else
    redirect_to :controller => "pictures", :action => 'new'
    end

  end
  def show
    @picture = Picture.find(params[:id])
    puts "bbbbbbbbbbbbbbbbbbbbbbbb",@picture.inspect


  end
  def index
  @pictures = Picture.all
  end

   def destroy
     puts "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",params.inspect
     @picture = Picture.find(params[:id])

     @picture.destroy
     redirect_to :controller => "pictures", :action => 'index'




   end



end
private
def pic_params
  params[:picture].permit(:pic)# (:pic_file_name,:pic_content_type,:pic_file_size)
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!

  def new
  @post = Post.new
  end

  def create
    puts "1111111111111111",params.inspect
    @post = Post.new(posts_params)
   if @post.save
     flash[:success] = "Post SuccessFully Created"
    redirect_to post_path(@post)
   else
     render "new"
  end
  end

  def show
   if current_user
   @post = Post.find(params[:id])
   end

  end

  def index
  @posts = current_user.posts
  end

  def edit
  @post = Post.find(params[:id])
  end

  def update
  @post = Post.find(params[:id])
    if @post.update_attributes(params[:post].permit(:title, :text,:user_id))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path
    end
  end
end

private

def posts_params
  params[:post].permit(:title, :text,:user_id)

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>


<div id="user_nav">
  <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>


<%= yield %>

</body>
</html>

app/views/pictures/index.erb
<div image_gallery style="float:left;width: 100%;height: 100%;margin: 35px 0px 20px 50px">
  <div image_gallery style="float:left;width: 100%;height: 100%;">
  <%= link_to 'Posts Portion', :controller => "posts", :action => 'index', :style => "float:left;width:100%;"%>
    </div>
  <div image_gallery style="float:left;width: 100%;height: 100%;">
  <%= link_to 'Upload New Picture', :controller => "pictures", :action => 'new', :style => 'float:leftwidth:100%;' %>
  </div>
  </div>

<% @pictures.each do |a| %>
    <div image_gallery style="float:left;width: 40%;height: 40%;margin: 35px 0px 20px 50px">

      <%= image_tag a.pic.url(:thumb) %>
      <%#=  link_to "Delete Piucture",  %>
      <%= link_to "Delete", picture_path(a), method: :delete, data: {confirm: "Are You Sure"}  %>

    </div>
<% end %>

app/views/pictures/new.erb
<!--# First line should be-->
 <%= form_for @picture, :html => { :multipart => true } do |f| %>
    <% if @picture.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@picture.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
            <% @picture.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
 <!--# Then, add the file_field fields.-->
   <!--<p>-->
     <!--<b><%#= f.label :attach %> </b><br/>-->
  <!--<%#= f.file_field :attach %>-->
   <!--</p>-->
  <p>
     <b> <%= f.label :pic %> </b><br/>
     <%= f.file_field :pic %>
   </p>
  <p>
     <b> <%= f.submit  %> </b><br/>

   </p>

 <% end %>
<%= link_to "Gallery", :controller => 'pictures',:action => 'index'  %>

app/views/pictures/show.erb
<%= image_tag @picture.pic.url(:thumb) %>
<%= link_to "Back To Picture", :controller => "pictures", :action => "index" %>

app/views/posts/_form.erb
<div id="flash_notices">
  <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
        <button class="close" data-dismiss="alert">×</button>
      </div>
  <% end %>
</div>
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title  %>
      <%= f.hidden_field "user_id", :value => current_user.id %>
      <%#= current_user.id %>
    </p>
    <p>
      <%= f.label :text  %>
      <%= f.text_area :text  %>
    </p>
    <p>
      <%= f.submit  %>
    </p>
<% end %>

app/views/posts/edit.erb
<%= render "form" %>

app/views/posts/index.erb
<h1>Listings Posts</h1>
<table>
<tr>
  <th>Title</th>
  <th>Text</th>
  <th>Show</th>
  <th>Update</th>
  <th>Delete</th>
</tr>
<% @posts.each do |post| %>
  <tr>
   <td><%= post.title %></td>
   <td><%= post.text %></td>
   <td><%= link_to "Show", post_path(post)  %></td>
   <td><%= link_to "Edit", edit_post_path(post)  %></td>
   <td><%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are You Sure"}  %></td>


  </tr>
      <% end %>

</table>
<%= link_to "New Post", :controller => "posts", :action => "new" %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render "form" %>
<%= link_to "Back To Posts", posts_path %>

app/views/posts/show.erb
<div id="flash_notices">
  <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
        <button class="close" data-dismiss="alert">×</button>
      </div>
  <% end %>
</div>

<p>
  <strong>Title</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Text</strong>
  <%= @post.text%>
</p>
<%= link_to "Back To Posts", :controller => "posts", :action => "index" %>
<!--/**=require conquer/bootstrap/css/bootstrap.min.css-->
<!--/**=require conquer/bootstrap/css/bootstrap-responsive.min.css*/-->
<!--/**=require conquer/font-awesome/css/font-awesome.css*/-->
<!--/**=require conquer/css/style.css*/-->
<!--/**=require conquer/css/style_responsive.css*/-->
<!--/**=require conquer/css/style_grey.css*/-->
<!--/**=require conquer/fancybox/source/jquery.fancybox.css*/-->
<!--/**=require conquer/fancybox/source/jquery.fancybox.css*/-->
<!--/**=require conquer/gritter/css/jquery.gritter.css*/-->
<!--/**=require conquer/uniform/css/uniform.default.css*/-->
<!--/**=require conquer/chosen-bootstrap/chosen/chosen.css*/-->
<!--/**=require conquer/bootstrap-daterangepicker/daterangepicker.css*/-->
<!--/**=require conquer/fullcalendar/fullcalendar/bootstrap-fullcalendar.css*/-->
<!--/**=require conquer/jqvmap/jqvmap/jqvmap.css*/-->
<!--/**=require shared_app_css*/-->
<!--/**=require apprise-v2*/-->
<!--/**=require conquer/bootstrap-datepicker/css/datepicker.css*/-->
<!--/**=require conquer/bootstrap-timepicker/compiled/timepicker.css*/-->
<!--/**=require conquer/bootstrap-daterangepicker/daterangepicker.css*/-->
<!--/**=require conquer/clockface/css/clockface*/-->
<!--/**=require conquer/data-tables/DT_bootstrap.css*/-->
<!--/**=require apprise*/-->
<!--/**=require bootstrap-datetimepicker.min*/-->
<!--/**=require jquery.treetable.css*/-->
<!--/**=require screen.css*/-->
<!--/**/-->

app/views/welcome/index.html.erb
<%= link_to 'New Post',:controller => 'posts', :action => "new" %>